// Generated by idrcad after solving: Solver-laid-out electronics front panel

panel_width = 116.900000;
panel_depth = 85.700000;
display_x = 58.450000;
display_y = 42.850000;
encoder_x = 100.700000;
usb_y = 15.900000;
assert((2.000000 * display_x) == panel_width, "Display must be horizontally centred");
assert((2.000000 * display_y) == panel_depth, "Display must be vertically centred");
assert(52.500000 > 0.000000, "Display width must be positive");
assert(30.500000 > 0.000000, "Display depth must be positive");
assert(26.250000 <= display_x, "Display must remain inside the rectangle's left edge");
assert((display_x + 26.250000) <= panel_width, "Display must remain inside the rectangle's right edge");
assert(15.250000 <= display_y, "Display must remain inside the rectangle's front edge");
assert((display_y + 15.250000) <= panel_depth, "Display must remain inside the rectangle's back edge");
assert(13.400000 > 0.000000, "USB width must be positive");
assert(7.400000 > 0.000000, "USB depth must be positive");
assert(6.700000 <= display_x, "USB must remain inside the rectangle's left edge");
assert((display_x + 6.700000) <= panel_width, "USB must remain inside the rectangle's right edge");
assert(3.700000 <= usb_y, "USB must remain inside the rectangle's front edge");
assert((usb_y + 3.700000) <= panel_depth, "USB must remain inside the rectangle's back edge");
assert(4.000000 > 0.000000, "Hole radius must be positive");
assert(4.000000 <= encoder_x, "Hole must remain inside the rectangle's left edge");
assert((encoder_x + 4.000000) <= panel_width, "Hole must remain inside the rectangle's right edge");
assert(4.000000 <= display_y, "Hole must remain inside the rectangle's front edge");
assert((display_y + 4.000000) <= panel_depth, "Hole must remain inside the rectangle's back edge");
assert(1.600000 > 0.000000, "Hole radius must be positive");
assert(1.600000 <= (1.600000 + 5.000000), "Hole must remain inside the rectangle's left edge");
assert(((1.600000 + 5.000000) + 1.600000) <= panel_width, "Hole must remain inside the rectangle's right edge");
assert(1.600000 <= (1.600000 + 5.000000), "Hole must remain inside the rectangle's front edge");
assert(((1.600000 + 5.000000) + 1.600000) <= panel_depth, "Hole must remain inside the rectangle's back edge");
assert(1.600000 > 0.000000, "Hole radius must be positive");
assert(1.600000 <= (panel_width - (1.600000 + 5.000000)), "Hole must remain inside the rectangle's left edge");
assert(((panel_width - (1.600000 + 5.000000)) + 1.600000) <= panel_width, "Hole must remain inside the rectangle's right edge");
assert(1.600000 <= (1.600000 + 5.000000), "Hole must remain inside the rectangle's front edge");
assert(((1.600000 + 5.000000) + 1.600000) <= panel_depth, "Hole must remain inside the rectangle's back edge");
assert(1.600000 > 0.000000, "Hole radius must be positive");
assert(1.600000 <= (1.600000 + 5.000000), "Hole must remain inside the rectangle's left edge");
assert(((1.600000 + 5.000000) + 1.600000) <= panel_width, "Hole must remain inside the rectangle's right edge");
assert(1.600000 <= (panel_depth - (1.600000 + 5.000000)), "Hole must remain inside the rectangle's front edge");
assert(((panel_depth - (1.600000 + 5.000000)) + 1.600000) <= panel_depth, "Hole must remain inside the rectangle's back edge");
assert(1.600000 > 0.000000, "Hole radius must be positive");
assert(1.600000 <= (panel_width - (1.600000 + 5.000000)), "Hole must remain inside the rectangle's left edge");
assert(((panel_width - (1.600000 + 5.000000)) + 1.600000) <= panel_width, "Hole must remain inside the rectangle's right edge");
assert(1.600000 <= (panel_depth - (1.600000 + 5.000000)), "Hole must remain inside the rectangle's front edge");
assert(((panel_depth - (1.600000 + 5.000000)) + 1.600000) <= panel_depth, "Hole must remain inside the rectangle's back edge");
assert((((display_x + 26.250000) + 12.000000) + 4.000000) <= encoder_x, "Encoder must sit at least 12 mm to the right of the display");
assert(((encoder_x + 4.000000) + 4.000000) <= ((panel_width - (1.600000 + 5.000000)) - 1.600000), "Encoder must clear the right mounting screws");
assert(((usb_y + 3.700000) + 8.000000) <= (display_y - 15.250000), "USB socket must sit at least 8 mm below the display");
assert((((1.600000 + 5.000000) + 1.600000) + 4.000000) <= (usb_y - 3.700000), "USB socket must clear the lower mounting screws");
assert((((1.600000 + 5.000000) + 1.600000) + 4.000000) <= (display_x - 26.250000), "Display must clear the left mounting screws");
assert(((display_x + 26.250000) + 4.000000) <= ((panel_width - (1.600000 + 5.000000)) - 1.600000), "Display must clear the right mounting screws");
assert((((1.600000 + 5.000000) + 1.600000) + 4.000000) <= (display_y - 15.250000), "Display must clear the lower mounting screws");
assert(((display_y + 15.250000) + 4.000000) <= ((panel_depth - (1.600000 + 5.000000)) - 1.600000), "Display must clear the upper mounting screws");

let($fn = 64) {
  union() {
    color(c = "steelblue") {
      difference() {
        cube(size = [panel_width, panel_depth, 3.000000], center = false);
        translate(v = [display_x, display_y, 1.500000]) {
          cube(size = [52.500000, 30.500000, (3.000000 + 2.000000)], center = true);
        }
        translate(v = [display_x, usb_y, 1.500000]) {
          cube(size = [13.400000, 7.400000, (3.000000 + 2.000000)], center = true);
        }
        translate(v = [encoder_x, display_y, 1.500000]) {
          cylinder(h = (3.000000 + 2.000000), r1 = 4.000000, r2 = 4.000000, center = true);
        }
        translate(v = [(1.600000 + 5.000000), (1.600000 + 5.000000), 1.500000]) {
          cylinder(h = (3.000000 + 2.000000), r1 = 1.600000, r2 = 1.600000, center = true);
        }
        translate(v = [(panel_width - (1.600000 + 5.000000)), (1.600000 + 5.000000), 1.500000]) {
          cylinder(h = (3.000000 + 2.000000), r1 = 1.600000, r2 = 1.600000, center = true);
        }
        translate(v = [(1.600000 + 5.000000), (panel_depth - (1.600000 + 5.000000)), 1.500000]) {
          cylinder(h = (3.000000 + 2.000000), r1 = 1.600000, r2 = 1.600000, center = true);
        }
        translate(v = [(panel_width - (1.600000 + 5.000000)), (panel_depth - (1.600000 + 5.000000)), 1.500000]) {
          cylinder(h = (3.000000 + 2.000000), r1 = 1.600000, r2 = 1.600000, center = true);
        }
      }
    }
    color(c = "black") {
      translate(v = [display_x, display_y, (3.000000 + 1.000000)]) {
        cube(size = [52.000000, 30.000000, 2.000000], center = true);
      }
    }
    color(c = "orange") {
      translate(v = [encoder_x, display_y, 3.000000]) {
        cylinder(h = 10.000000, r1 = 8.000000, r2 = 8.000000, center = false);
      }
    }
    color(c = "silver") {
      translate(v = [display_x, usb_y, (3.000000 + 2.000000)]) {
        cube(size = [13.000000, 7.000000, 4.000000], center = true);
      }
    }
    color(c = "silver") {
      translate(v = [(1.600000 + 5.000000), (1.600000 + 5.000000), (3.000000 + 1.000000)]) {
        cylinder(h = 2.000000, r1 = 3.000000, r2 = 3.000000, center = true);
      }
    }
    color(c = "silver") {
      translate(v = [(panel_width - (1.600000 + 5.000000)), (1.600000 + 5.000000), (3.000000 + 1.000000)]) {
        cylinder(h = 2.000000, r1 = 3.000000, r2 = 3.000000, center = true);
      }
    }
    color(c = "silver") {
      translate(v = [(1.600000 + 5.000000), (panel_depth - (1.600000 + 5.000000)), (3.000000 + 1.000000)]) {
        cylinder(h = 2.000000, r1 = 3.000000, r2 = 3.000000, center = true);
      }
    }
    color(c = "silver") {
      translate(v = [(panel_width - (1.600000 + 5.000000)), (panel_depth - (1.600000 + 5.000000)), (3.000000 + 1.000000)]) {
        cylinder(h = 2.000000, r1 = 3.000000, r2 = 3.000000, center = true);
      }
    }
  }
}
